routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProfileInfoController;
use App\Http\Controllers\HistoricalSitesController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});



Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');


    Route::patch('/profile-info/{userInfo}', [ProfileInfoController::class, 'update'])->name('profile.info.update');

    Route::get('/dashboard', [HistoricalSitesController::class, 'dashboard'])->name('dashboard');
    Route::get('/historical-site-show/{historicalSite}', [HistoricalSitesController::class, 'historicalSite'])->name('historical.site.show');
});

Route::get('/', [HistoricalSitesController::class, 'index'])->name('historical-sites.index');
Route::get('/historical-site/{historicalSite}', [HistoricalSitesController::class, 'show'])->name('historical.site.show');

Route::post('/store-comment', [\App\Http\Controllers\Comment::class, 'storeComment'])->name('store.comment')->middleware('auth');
Route::post('/destroy-comment', [\App\Http\Controllers\Comment::class, 'destroyComment'])->name('destroy.comment')->middleware('auth');

Route::post('/store-comment-answer', [\App\Http\Controllers\CommentAnswer::class, 'storeCommentAnswer'])->name('store.comment.answer')->middleware('auth');
Route::post('/destroy-comment-answer', [\App\Http\Controllers\CommentAnswer::class, 'destroyCommentAnswer'])->name('destroy.comment.answer')->middleware('auth');

Route::post('/store-comment-like', [\App\Http\Controllers\CommentLikeDislikeDataController::class, 'storeCommentLike'])->name('store.comment.like')->middleware('auth');

Route::post('/visited-historical-site', [\App\Http\Controllers\HistoricalSitesController::class, 'visitedHistoricalSite'])->name('visited.historical.site')->middleware('auth');
Route::post('/rating-historical-site', [\App\Http\Controllers\HistoricalSitesController::class, 'ratingHistoricalSite'])->name('rating.historical.site')->middleware('auth');

Route::get('/visited-historical-sites', [\App\Http\Controllers\HistoricalSitesController::class, 'visitedHistoricalSites'])->name('visited.historical.sites')->middleware('auth');

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/index', [\App\Http\Controllers\Admin\AdminController::class, 'index'])->name('index');

    Route::get('/show-users', [\App\Http\Controllers\Admin\AdminController::class, 'showUsers'])->name('show.users');
    Route::get('/set-user-role/{user}', [\App\Http\Controllers\Admin\AdminController::class, 'setUserRole'])->name('set.user.role');

    Route::post('/update-user-role/{user}', [\App\Http\Controllers\Admin\AdminController::class, 'updateUserRole'])->name('update.user.role');

    Route::get('/create-role', [\App\Http\Controllers\Admin\AdminController::class, 'createRole'])->name('create.role');
    Route::post('/store-role', [\App\Http\Controllers\Admin\AdminController::class, 'storeRole'])->name('store.role');

    Route::get('/create-permission-role/{role}', [\App\Http\Controllers\Admin\AdminController::class, 'createPermissionRole'])->name('create.permission.role');
    Route::post('/update-permission-role/{role}', [\App\Http\Controllers\Admin\AdminController::class, 'updatePermissionRole'])->name('update.permission.role');

    Route::get('/show-historical-sites', [\App\Http\Controllers\Admin\AdminController::class, 'showHistoricalSites'])->name('show.historical.sites');
    Route::get('/show-historical-site/{historicalSite}', [\App\Http\Controllers\Admin\AdminController::class, 'showHistoricalSite'])->name('show.historical.site');

    Route::get('/create-historical-site', [\App\Http\Controllers\Admin\AdminController::class, 'createHistoricalSite'])->name('create.historical.site');
    Route::post('/store-historical-site', [\App\Http\Controllers\Admin\AdminController::class, 'storeHistoricalSite'])->name('store.historical.site');

    Route::get('/edit-historical-site/{historicalSite}', [\App\Http\Controllers\Admin\AdminController::class, 'editHistoricalSite'])->name('edit.historical.site');
    Route::patch('/update-historical-site/{historicalSite}', [\App\Http\Controllers\Admin\AdminController::class, 'updateHistoricalSite'])->name('update.historical.site');
});


require __DIR__.'/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/admin/create-historical-site.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Admin Panel Add Historical Site') }}
        </h2>
    </x-slot>

    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-6 mt-6">
        <a id="app-button" href="{{ route('admin.show.historical.sites') }}" class="button">Back</a>
        <div class="p-4 sm:p-8 bg-white dark:bg-gray-800 shadow sm:rounded-lg">
            <div class="max-w-xl">
                <section>
                    <form method="post" enctype="multipart/form-data" action="{{ route('admin.store.historical.site') }}" class="mt-6 space-y-6">
                        @csrf

                        <div>
                            <x-input-label for="name" :value="__('Name')" />
                            <x-text-input id="name" name="name" type="text" class="mt-1 block w-full" :value="old('name')" autofocus />
                            <x-input-error class="mt-2" :messages="$errors->get('name')" />
                        </div>

                        <div>
                            <x-input-label for="data" :value="__('Data')" />
                            <textarea id="data" name="data" class="mt-1 block w-full" autofocus>{{ old('data') }}</textarea>
                            <x-input-error class="mt-2" :messages="$errors->get('data')" />
                        </div>

                        <div>
                            <x-input-label for="confirmed" :value="__('Confirmed')" />
                            <select id="confirmed" name="confirmed" class="border-gray-300 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-300 focus:border-indigo-500 dark:focus:border-indigo-600 focus:ring-indigo-500 dark:focus:ring-indigo-600 rounded-md shadow-sm mt-1 block w-full" autofocus>
                                <option value="0">Not Confirmed</option>
                                <option value="1">Confirmed</option>
                            </select>
                            <x-input-error class="mt-2" :messages="$errors->get('confirmed')" />
                        </div>

                        <div>
                            <x-input-label for="historical-site-image" :value="__('Historical Site Image')" />
                            <x-text-input id="historical-site-image" name="historical_site_image" type="file" class="mt-1 block w-full" autofocus />
                            <x-input-error class="mt-2" :messages="$errors->get('historical_site_image')" />
                        </div>

                        <div class="flex items-center gap-4">
                            <x-primary-button>{{ __('Save') }}</x-primary-button>

                            @if (session('status') === 'historical-site-store')
                                <p
                                    x-data="{ show: true }"
                                    x-show="show"
                                    x-transition
                                    x-init="setTimeout(() => show = false, 2000)"
                                    class="text-sm text-gray-600 dark:text-gray-400"
                                >{{ __('Saved.') }}</p>
                            @endif

                        </div>
                    </form>
                </section>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/admin/create-permission-role.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Admin Panel Add Permission to Role') }}
        </h2>
    </x-slot>

    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-6 mt-6">
        <a id="app-button" href="{{ route('admin.create.role') }}" class="button">Back</a>
        <div class="p-4 sm:p-8 bg-white dark:bg-gray-800 shadow sm:rounded-lg">
            <div class="max-w-xl">
                <section>
                    <h3>{{__('Add permissions for ' . $role->name . ' role!')}}</h3>
                    <form method="post" action="{{ route('admin.update.permission.role', [$role->id]) }}" class="mt-6 space-y-6">
                        @csrf

                        <input type="hidden" name="class" value="{{ $class }}">
                        <div>
                            @foreach($methodsInAdminControllerFiltered as $action)
                                @php
                                    $isChecked = '';
                                    foreach ($role->permissions as $permission) {
                                        if ($permission->controller == $class && $permission->action == $action->name) {
                                            $isChecked = 'checked';
                                        }
                                    }
                                @endphp
                                <x-input-label for="{{ $action->name }}" value="{{ $action->name }}" />
                                <input type="checkbox" value="{{ $action->name }}" id="{{ $action->name }}" {{ $isChecked }} name="actions[]">
                            @endforeach
                            <x-input-error class="mt-2" :messages="$errors->get('actions[]')" />
                        </div>

                        <div class="flex items-center gap-4">
                            <x-primary-button>{{ __('Save') }}</x-primary-button>

                            @if (session('status') === 'role-permission-store')
                                <p
                                    x-data="{ show: true }"
                                    x-show="show"
                                    x-transition
                                    x-init="setTimeout(() => show = false, 2000)"
                                    class="text-sm text-gray-600 dark:text-gray-400"
                                >{{ __('Saved.') }}</p>
                            @endif
                        </div>
                    </form>
                </section>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/admin/create-role.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Admin Panel Create Role') }}
        </h2>
    </x-slot>

    <table>
        <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Set Permission Role</th>
        </tr>
        </thead>
        <tbody>
        @foreach($roles as $role)
            <tr>
                <td data-label="Id">{{ $role->id }}</td>
                <td data-label="Name">{{ $role->name }}</td>
                <td data-label="Set Permission Role">
                    <a id="table-button" href="{{ route('admin.create.permission.role', [$role->id]) }}" >Set Permission Role</a>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>

    <div id="pagination">
        {{ $roles->links() }}
    </div>

    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-6 mt-6">
        <div class="p-4 sm:p-8 bg-white dark:bg-gray-800 shadow sm:rounded-lg">
            <div class="max-w-xl">
                <section>
                    <form method="post" action="{{ route('admin.store.role') }}" class="mt-6 space-y-6">
                        @csrf

                        <div>
                            <x-input-label for="role" :value="__('Role')" />
                            <x-text-input id="role" name="name" type="text" class="mt-1 block w-full" :value="old('name')" autofocus />
                            <x-input-error class="mt-2" :messages="$errors->get('name')" />
                        </div>

                        <div class="flex items-center gap-4">
                            <x-primary-button>{{ __('Save') }}</x-primary-button>

                            @if (session('status') === 'role-store')
                                <p
                                    x-data="{ show: true }"
                                    x-show="show"
                                    x-transition
                                    x-init="setTimeout(() => show = false, 2000)"
                                    class="text-sm text-gray-600 dark:text-gray-400"
                                >{{ __('Saved.') }}</p>
                            @endif
                        </div>
                    </form>
                </section>
            </div>
        </div>
    </div>

    <div id="button-container">
        <a id="app-button" href="{{ route('admin.index') }}" class="button">Back</a>
    </div>
</x-app-layout>

resources/views/admin/edit-historical-site.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Admin Panel Add Historical Site') }}
        </h2>
    </x-slot>

    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-6 mt-6">
        <a id="app-button" href="{{ route('admin.show.historical.site', [$historicalSite->id]) }}" class="button">Back</a>
        <div class="p-4 sm:p-8 bg-white dark:bg-gray-800 shadow sm:rounded-lg">
            <div class="max-w-xl">
                <section>
                    <form method="post" enctype="multipart/form-data" action="{{ route('admin.update.historical.site', [$historicalSite->id]) }}" class="mt-6 space-y-6">
                        @csrf
                        @method('patch')

                        <div>
                            <x-input-label for="name" :value="__('Name')" />
                            <x-text-input id="name" name="name" type="text" class="mt-1 block w-full" :value="old('name', $historicalSite->name)" autofocus />
                            <x-input-error class="mt-2" :messages="$errors->get('name')" />
                        </div>

                        <div>
                            <x-input-label for="data" :value="__('Data')" />
                            <textarea id="data" name="data" class="mt-1 block w-full" autofocus>{{ old('data', $historicalSite->data) }}</textarea>
                            <x-input-error class="mt-2" :messages="$errors->get('data')" />
                        </div>

                        <div>
                            <x-input-label for="confirmed" :value="__('Confirmed')" />
                            <select id="confirmed" name="confirmed" class="border-gray-300 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-300 focus:border-indigo-500 dark:focus:border-indigo-600 focus:ring-indigo-500 dark:focus:ring-indigo-600 rounded-md shadow-sm mt-1 block w-full" autofocus>
                                <option value="0" {{ old('confirmed', $historicalSite->confirmed) == '0' ? 'selected' : '' }}>Not Confirmed</option>
                                <option value="1" {{ old('confirmed', $historicalSite->confirmed) == '1' ? 'selected' : '' }}>Confirmed</option>
                            </select>
                            <x-input-error class="mt-2" :messages="$errors->get('confirmed')" />
                        </div>

                        <div>
                            <x-input-label for="historical-site-image" :value="__('Historical Site Image')" />
                            <image src="{{ $historicalSite->getHistoricalSitePictureUrl('historicalSiteImage', 'thumb') }}"></image>
                            <x-text-input id="historical-site-image" name="historical_site_image" type="file" class="mt-1 block w-full" autofocus />
                            <x-input-error class="mt-2" :messages="$errors->get('historical_site_image')" />
                        </div>

                        <div class="flex items-center gap-4">
                            <x-primary-button>{{ __('Save') }}</x-primary-button>

                            @if (session('status') === 'historical-site-update')
                                <p
                                    x-data="{ show: true }"
                                    x-show="show"
                                    x-transition
                                    x-init="setTimeout(() => show = false, 2000)"
                                    class="text-sm text-gray-600 dark:text-gray-400"
                                >{{ __('Saved.') }}</p>
                            @endif

                        </div>
                    </form>
                </section>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/admin/historical-site.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Admin Panel Show Historical Site') }}
        </h2>
    </x-slot>
    <x-historical-site-admin :historicalSite="$historicalSite"/>
</x-app-layout>

resources/views/admin/historical-sites.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Admin Panel Show Historical Sites') }}
        </h2>
    </x-slot>
    <x-search-form-historical-site />
    <table>
        <thead>
        <tr>
            <th>Id</th>
            <th>Historical Site Name</th>
            <th>Historical Site Info</th>
            <th>Is Confirmed Historical Site</th>
            <th>Show Historical Site</th>
        </tr>
        </thead>
        <tbody>
        @foreach($historicalSites as $historicalSite)
            <tr>
                <td data-label="Id">{{ $historicalSite->id }}</td>
                <td data-label="Historical Site Name">{{ $historicalSite->name }}</td>
                <td data-label="Historical Site Info">{{ Str::limit($historicalSite->data, 50, $end = '...') }}</td>
                <td data-label="Is Confirmed Historical Site">{{ $historicalSite->confirmed ? 'Yes' : 'No' }}</td>
                <td data-label="Show Historical Site">
                    <a id="table-button" href="{{ route('admin.show.historical.site', [$historicalSite->id]) }}" >Show Historical Site</a>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>

    <div id="pagination">
        {{ $historicalSites->links() }}
    </div>

    <div id="button-container">
        <a id="app-button" href="{{ route('admin.index') }}" class="button">Back</a>
        <a id="app-button" href="{{ route('admin.create.historical.site') }}" class="button">Add</a>
    </div>
</x-app-layout>

resources/views/admin/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Admin Panel Index') }}
        </h2>
    </x-slot>

    <div id="admin-button-menu">
        <a id="app-button" href="{{ route('admin.show.users') }}" class="button">Show All Users</a>
        <a id="app-button" href="{{ route('admin.create.role') }}" class="button">Create Role</a>
        <a id="app-button" href="{{ route('admin.show.historical.sites') }}" class="button">Historical Sites</a>
    </div>
</x-app-layout>

resources/views/admin/set-user-role.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Admin Panel Set User Role') }}
        </h2>
    </x-slot>
    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-6 mt-6">
        <a id="app-button" href="{{ route('admin.show.users') }}" class="button">Back</a>
        <div class="p-4 sm:p-8 bg-white dark:bg-gray-800 shadow sm:rounded-lg">
            <div class="max-w-xl">
                <section>
                    <form method="post" action="{{ route('admin.update.user.role', [$userData['userId']]) }}" class="mt-6 space-y-6">
                        @csrf

                        <div>
                            <x-input-label for="role" :value="__('Roles')" />

                            <select id="role" name="role" class="border-gray-300 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-300 focus:border-indigo-500 dark:focus:border-indigo-600 focus:ring-indigo-500 dark:focus:ring-indigo-600 rounded-md shadow-sm mt-1 block w-full" autofocus>
                                <option value=""></option>
                                @foreach($roles as $role)
                                    <option value="{{ $role->id }}" {{ old('role', $role->name) == $userData['userRoleName'] ? 'selected' : '' }}>{{ $role->name }}</option>
                                @endforeach
                            </select>
                            <x-input-error class="mt-2" :messages="$errors->get('role')" />
                        </div>

                        <div class="flex items-center gap-4">
                            <x-primary-button>{{ __('Save') }}</x-primary-button>

                            @if (session('status') === 'role-updated')
                                <p
                                    x-data="{ show: true }"
                                    x-show="show"
                                    x-transition
                                    x-init="setTimeout(() => show = false, 2000)"
                                    class="text-sm text-gray-600 dark:text-gray-400"
                                >{{ __('Saved.') }}</p>
                            @endif
                        </div>
                    </form>
                </section>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/admin/show-users.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Admin Panel Show Users') }}
        </h2>
    </x-slot>
    <x-search-form-user />
    <table>
        <thead>
        <tr>
            <th>Id</th>
            <th>Username</th>
            <th>Email</th>
            <th>First Name</th>
            <th>Middle Name</th>
            <th>Last Name</th>
            <th>Set Role</th>
        </tr>
        </thead>
        <tbody>
            @foreach($users as $user)
                <tr>
                    <td data-label="Id">{{ $user->id }}</td>
                    <td data-label="Username">{{ $user->username }}</td>
                    <td data-label="Email">{{ $user->email }}</td>
                    <td data-label="First Name">{{ $user->userInfo->first_name }}</td>
                    <td data-label="Middle Name">{{ $user->userInfo->middle_name }}</td>
                    <td data-label="Last Name">{{ $user->userInfo->last_name }}</td>
                    <td data-label="Set Role">
                        <a id="table-button" href="{{ route('admin.set.user.role',[$user->id]) }}" >Set Role</a>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div id="pagination">
        {{ $users->links() }}
    </div>

    <div id="button-container">
        <a id="app-button" href="{{ route('admin.index') }}" class="button">Back</a>
    </div>
</x-app-layout>